[package]
name = "stock-checker-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "gzip"] }
regex = "1.10"
rayon = "1.10"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
